In [2]:
import pandas as pd
import numpy as np

### 데이터 불러오기

In [3]:
df1 = pd.read_csv('./data/H_data/T20_2019_1백만.1.csv', encoding = 'cp949')
df1.head()

기준년도  가입자 일련번호   진료내역일련번호  성별코드  연령대코드  시도코드    요양개시일자  서식코드  진료과목코드  \
0  2019         1  104243474     2     12    46  20191104     3       5   
1  2019         1  107479370     2     12    46  20190806     3       1   
2  2019         1  106881883     2     12    46  20190920     3       1   
3  2019         1  109043837     2     12    46  20190807     2       1   
4  2019         1  103174392     2     12    46  20190318     3      13   

   주상병코드  부상병코드  요양일수  입내원일수  심결가산율  심결요양급여비용총액  심결본인부담금  심결보험자부담금  총처방일수  \
0   M751   M750     1      1   0.25       19240     9600      9640      0   
1  E1164   N308     1      1   0.25      145680    72800     72880      0   
2   N308  E1164     1      1   0.25       13240     6600      6640      3   
3  E1164   N308     7     21   0.25      861590   205810    655780      0   
4  H6531   J303     1      1   0.15       48440    14500     33940      3   

   데이터 기준일자  
0  20201222  
1  20201222  
2  20201222  
3  20201222  
4  20201222

In [4]:
var_list = ['연령대코드','성별코드', '주상병코드', '부상병코드', '입내원일수']
data = df1[var_list]
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4624144 entries, 0 to 4624143
Data columns (total 5 columns):
 #   Column  Dtype 
---  ------  ----- 
 0   연령대코드   int64 
 1   성별코드    int64 
 2   주상병코드   object
 3   부상병코드   object
 4   입내원일수   int64 
dtypes: int64(3), object(2)
memory usage: 176.4+ MB


In [7]:
df2 = pd.read_excel('./data/illness_ji.xlsx')
df2.head()

순위 주상병코드
0   0  J209
1   1   J40
2   2    F_
3   3  J304
4   4  L239

In [5]:
df3 = pd.read_excel('./data/illness_jiji.xlsx')
df3.head()

순위  질병코드
0   0  J209
1   1   J40
2   2    F_
3   3  J304
4   4  L239

### 질병코드에 해당하는 값(순위)으로 치환

In [8]:
# 질병코드에 해당하는 값 치환하고 NaN은 사라짐

df2_ju = pd.merge(data, df2)
df2_ju

연령대코드  성별코드 주상병코드 부상병코드  입내원일수  순위
0           12     2  M751  M750      1  31
1           12     2  M751  M750      1  31
2           12     2  M751  M750      1  31
3           12     2  M751  M750      1  31
4           12     2  M751  M750      1  31
...        ...   ...   ...   ...    ...  ..
2600764      2     2  E228    E_      1  78
2600765      3     2  E228  E230      1  78
2600766      3     2  E228  E230      1  78
2600767      3     2  E228  E230      1  78
2600768      3     2  E228  E230      1  78

[2600769 rows x 6 columns]

In [9]:
# how 옵션으로 NaN값 남겨줌 
pd.merge(data, df2, how='outer',on= '주상병코드')


# 양쪽 컬럼이름이 다를때 합치는 법
df3_1 = pd.merge(data, df3, how='left', left_on='주상병코드', right_on='질병코드')
df3_1


# NaN 값 종류 확인하기
# set(data['주상병코드'].unique()) - set(df3['질병코드'].unique())

연령대코드  성별코드  주상병코드  부상병코드  입내원일수    순위   질병코드
0           12     2   M751   M750      1  31.0   M751
1           12     2  E1164   N308      1   NaN    NaN
2           12     2   N308  E1164      1   NaN    NaN
3           12     2  E1164   N308     21   NaN    NaN
4           12     2  H6531   J303      1   NaN    NaN
...        ...   ...    ...    ...    ...   ...    ...
4624139      9     2   T151  H1621      1   NaN    NaN
4624140      5     1   J060   J209      1  11.0   J060
4624141      5     1  M1996   K291      1   NaN    NaN
4624142      5     1   J060   J209      1  11.0   J060
4624143      5     1  J0390   J209      1  13.0  J0390

[4624144 rows x 7 columns]

In [12]:
print(df2_ju.head())
print(df3.head())

   연령대코드  성별코드 주상병코드 부상병코드  입내원일수  순위
0     12     2  M751  M750      1  31
1     12     2  M751  M750      1  31
2     12     2  M751  M750      1  31
3     12     2  M751  M750      1  31
4     12     2  M751  M750      1  31
   순위  질병코드
0   0  J209
1   1   J40
2   2    F_
3   3  J304
4   4  L239


In [10]:
data_ju = pd.merge(df2_ju, df3, how='left', left_on='주상병코드', right_on='질병코드')
data_ju

연령대코드  성별코드 주상병코드 부상병코드  입내원일수  순위_x  순위_y  질병코드
0           12     2  M751  M750      1    31    31  M751
1           12     2  M751  M750      1    31    31  M751
2           12     2  M751  M750      1    31    31  M751
3           12     2  M751  M750      1    31    31  M751
4           12     2  M751  M750      1    31    31  M751
...        ...   ...   ...   ...    ...   ...   ...   ...
2600764      2     2  E228    E_      1    78    78  E228
2600765      3     2  E228  E230      1    78    78  E228
2600766      3     2  E228  E230      1    78    78  E228
2600767      3     2  E228  E230      1    78    78  E228
2600768      3     2  E228  E230      1    78    78  E228

[2600769 rows x 8 columns]

In [10]:
varl = ['연령대코드','성별코드', '부상병코드', '입내원일수', '순위']
df2_ju_1 = df2_ju[varl]
df2_ju_1.head()
df2_ju_1

연령대코드  성별코드 부상병코드  입내원일수  순위
0           12     2  M750      1  31
1           12     2  M750      1  31
2           12     2  M750      1  31
3           12     2  M750      1  31
4           12     2  M750      1  31
...        ...   ...   ...    ...  ..
2600764      2     2    E_      1  78
2600765      3     2  E230      1  78
2600766      3     2  E230      1  78
2600767      3     2  E230      1  78
2600768      3     2  E230      1  78

[2600769 rows x 5 columns]

In [11]:
data_23 = pd.merge(df2_ju_1, df3, how='right', left_on='부상병코드', right_on='질병코드')
data_23

연령대코드  성별코드 부상병코드  입내원일수  순위_x  순위_y  질병코드
0            9     1  J209      1    31     0  J209
1            9     1  J209      1    31     0  J209
2           14     1  J209      1    31     0  J209
3           16     2  J209      1    31     0  J209
4           11     1  J209      1    31     0  J209
...        ...   ...   ...    ...   ...   ...   ...
1537480      1     1  J180      1    77    83  J180
1537481      1     1  J180      1    77    83  J180
1537482      1     1  J180      1    77    83  J180
1537483      1     1  J180      1    77    83  J180
1537484      1     1  J180      1    77    83  J180

[1537485 rows x 7 columns]

In [12]:
varll = ['연령대코드','성별코드', '입내원일수', '순위_x', '순위_y']
data_231 = data_23[varll]
data_231.head()

연령대코드  성별코드  입내원일수  순위_x  순위_y
0      9     1      1    31     0
1      9     1      1    31     0
2     14     1      1    31     0
3     16     2      1    31     0
4     11     1      1    31     0

In [13]:
data_231 = data_231.rename(columns={'순위_x':'주상병코드'})
data_231 = data_231.rename(columns={'순위_y':'부상병코드'})

In [14]:
data_231

연령대코드  성별코드  입내원일수  주상병코드  부상병코드
0            9     1      1     31      0
1            9     1      1     31      0
2           14     1      1     31      0
3           16     2      1     31      0
4           11     1      1     31      0
...        ...   ...    ...    ...    ...
1537480      1     1      1     77     83
1537481      1     1      1     77     83
1537482      1     1      1     77     83
1537483      1     1      1     77     83
1537484      1     1      1     77     83

[1537485 rows x 5 columns]

### feature 데이터 확인

In [15]:
data_231.head()

연령대코드  성별코드  입내원일수  주상병코드  부상병코드
0      9     1      1     31      0
1      9     1      1     31      0
2     14     1      1     31      0
3     16     2      1     31      0
4     11     1      1     31      0

### train test 구분하기

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(data_231.iloc[:,:4],
                                                    data_231.iloc[:,4:], test_size = 0.33)

- 선형회귀 (소수점으로 나와서 실패)

In [40]:
from sklearn.linear_model import LinearRegression

In [42]:
model = LinearRegression(fit_intercept= True)
model

LinearRegression()

In [ ]:
LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [43]:
model.fit(X_train, y_train)

LinearRegression()

In [44]:
model.coef_

array([[ 0.29035947,  0.36081792, -0.31217571,  0.06444221]])

In [45]:
model.intercept_

array([15.34683511])

- 의사결정나무 (정확도가 너무 떨어져서 실패)

In [52]:
from sklearn import tree
model = tree.DecisionTreeClassifier()
model

DecisionTreeClassifier()

In [53]:
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [54]:
from sklearn.metrics import classification_report, confusion_matrix

In [55]:
print(confusion_matrix(y_test, model.predict(X_test)))

[[38967    63   164 ...     1     9     0]
 [ 2364    70    72 ...     0     1     0]
 [  102     6 31085 ...     0     1     1]
 ...
 [   11     1     9 ...    16     0     0]
 [  574     0    24 ...     0     9     0]
 [  149     5     4 ...     0     0     0]]


In [56]:
print(classification_report(y_test, model.predict(X_test)))

C:\Users\jhjh3\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\jhjh3\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           0       0.35      0.75      0.47     52212
           1       0.17      0.01      0.03      4910
           2       0.82      0.88      0.85     35224
           3       0.32      0.71      0.44     68395
           4       0.26      0.17      0.21      2962
           5       0.27      0.01      0.02     10060
           6       0.19      0.06      0.09      6725
           7       0.27      0.11      0.16      5914
           8       0.33      0.20      0.25      2766
           9       0.51      0.67      0.58      2145
          10       0.25      0.16      0.20      5885
          11       0.14      0.00      0.00      8818
          12       0.18      0.00      0.01     11575
          13       0.14      0.00      0.01     10203
          14       0.63      0.89      0.74     21624
          15       0.36      0.48      0.41     35969
          16       0.57      0.79      0.67     19668
          17       0.24    

C:\Users\jhjh3\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [60]:
data_231['부상병코드'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83],
      dtype=int64)

- knn

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [19]:
from sklearn.neighbors import KNeighborsClassifier

In [20]:
neigh3 = KNeighborsClassifier(n_neighbors=83, weights='distance')
neigh3.fit(X_train, y_train)

C:\Users\jhjh3\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=83, weights='distance')

In [ ]:
print('-------------- knn=3 data ---------------')
print(classification_report(y_test, neigh3.predict(X_test)))