In [1]:
import pandas as pd
import numpy as np

### 데이터 불러오기

In [3]:
df1 = pd.read_csv('./data/H_data/T20_2019_1백만.1.csv', encoding = 'cp949')
df1.head()

기준년도  가입자 일련번호   진료내역일련번호  성별코드  연령대코드  시도코드    요양개시일자  서식코드  진료과목코드  \
0  2019         1  104243474     2     12    46  20191104     3       5   
1  2019         1  107479370     2     12    46  20190806     3       1   
2  2019         1  106881883     2     12    46  20190920     3       1   
3  2019         1  109043837     2     12    46  20190807     2       1   
4  2019         1  103174392     2     12    46  20190318     3      13   

   주상병코드  부상병코드  요양일수  입내원일수  심결가산율  심결요양급여비용총액  심결본인부담금  심결보험자부담금  총처방일수  \
0   M751   M750     1      1   0.25       19240     9600      9640      0   
1  E1164   N308     1      1   0.25      145680    72800     72880      0   
2   N308  E1164     1      1   0.25       13240     6600      6640      3   
3  E1164   N308     7     21   0.25      861590   205810    655780      0   
4  H6531   J303     1      1   0.15       48440    14500     33940      3   

   데이터 기준일자  
0  20201222  
1  20201222  
2  20201222  
3  20201222  
4  20201222

### 필요한 데이터만 추출

In [4]:
var_list = ['연령대코드','성별코드', '주상병코드', '부상병코드', '입내원일수']
data = df1[var_list]
data.head()

연령대코드  성별코드  주상병코드  부상병코드  입내원일수
0     12     2   M751   M750      1
1     12     2  E1164   N308      1
2     12     2   N308  E1164      1
3     12     2  E1164   N308     21
4     12     2  H6531   J303      1

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4624144 entries, 0 to 4624143
Data columns (total 5 columns):
 #   Column  Dtype 
---  ------  ----- 
 0   연령대코드   int64 
 1   성별코드    int64 
 2   주상병코드   object
 3   부상병코드   object
 4   입내원일수   int64 
dtypes: int64(3), object(2)
memory usage: 176.4+ MB


### feature 데이터 만들기

#### 주상병코드 만들기

In [6]:
var_list = ['연령대코드', '성별코드']
data_x = data[var_list]
data_x.head()

연령대코드  성별코드
0     12     2
1     12     2
2     12     2
3     12     2
4     12     2

In [7]:
# 가장 앞 알파벳만 따로 추출
alpha = []
for i in data['주상병코드']:
    alpha.append(i[0])
alpha

['M',
 'E',
 'N',
 'E',
 'H',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'E',
 'M',
 'M',
 'M',
 'J',
 'M',
 'H',
 'M',
 'E',
 'M',
 'M',
 'E',
 'M',
 'M',
 'E',
 'M',
 'N',
 'M',
 'J',
 'M',
 'E',
 'H',
 'M',
 'M',
 'J',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'F',
 'F',
 'L',
 'F',
 'F',
 'F',
 'F',
 'F',
 'K',
 'K',
 'S',
 'K',
 'B',
 'J',
 'K',
 'K',
 'K',
 'J',
 'N',
 'H',
 'N',
 'K',
 'K',
 'N',
 'J',
 'K',
 'J',
 'E',
 'H',
 'J',
 'K',
 'K',
 'E',
 'H',
 'H',
 'J',
 'M',
 'M',
 'E',
 'S',
 'H',
 'E',
 'J',
 'K',
 'M',
 'E',
 'J',
 'E',
 'E',
 'E',
 'E',
 'N',
 'J',
 'J',
 'J',
 'S',
 'S',
 'S',
 'L',
 'S',
 'J',
 'S',
 'J',
 'M',
 'A',
 'L',
 'J',
 'J',
 'I',
 'L',
 'L',
 'I',
 'I',
 'I',
 'I',
 'I',
 'I',
 'I',
 'L',
 'I',
 'L',
 'I',
 'J',
 'J',
 'S',
 'J',
 'J',
 'J',
 'J',
 'J',
 'L',
 'H',
 'L',
 'J',
 'J',
 'K',
 'K',
 'H',
 'I',
 'M',
 'J',
 'L',
 'T',
 'K',
 'K',
 'T',
 'T',
 'J',
 'I',
 'T',
 'M',
 'I',
 'R',
 'I',
 'M',
 'I',
 'K',
 'S',
 'M',
 'S'

In [8]:
# 숫자로 변환
alnum = []
for i in alpha:
    alnum.append(ord(i) - 64)
alnum

[13,
 5,
 14,
 5,
 8,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 5,
 13,
 13,
 13,
 10,
 13,
 8,
 13,
 5,
 13,
 13,
 5,
 13,
 13,
 5,
 13,
 14,
 13,
 10,
 13,
 5,
 8,
 13,
 13,
 10,
 13,
 13,
 13,
 13,
 13,
 13,
 6,
 6,
 6,
 12,
 6,
 6,
 6,
 6,
 6,
 11,
 11,
 19,
 11,
 2,
 10,
 11,
 11,
 11,
 10,
 14,
 8,
 14,
 11,
 11,
 14,
 10,
 11,
 10,
 5,
 8,
 10,
 11,
 11,
 5,
 8,
 8,
 10,
 13,
 13,
 5,
 19,
 8,
 5,
 10,
 11,
 13,
 5,
 10,
 5,
 5,
 5,
 5,
 14,
 10,
 10,
 10,
 19,
 19,
 19,
 12,
 19,
 10,
 19,
 10,
 13,
 1,
 12,
 10,
 10,
 9,
 12,
 12,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 12,
 9,
 12,
 9,
 10,
 10,
 19,
 10,
 10,
 10,
 10,
 10,
 12,
 8,
 12,
 10,
 10,
 11,
 11,
 8,
 9,
 13,
 10,
 12,
 20,
 11,
 11,
 20,
 20,
 10,
 9,
 20,
 13,
 9,
 18,
 9,
 13,
 9,
 11,
 19,
 13,
 19,
 13,
 11,
 20,
 10,
 10,
 13,
 10,
 10,
 13,
 13,
 6,
 18,
 9,
 19,
 9,
 6,
 10,
 6,
 6,
 9,
 18,
 13,
 11,
 19,
 9,
 9,
 8,
 6,
 8,
 7,
 20,
 19,
 7,
 9,
 9,
 9,
 10,
 19,
 13,
 9,
 6,
 13,
 6,
 5,
 13,
 7,
 9,
 9,


In [9]:
# 컬럼 추가
data_x['주상병알파벳'] = alnum
data_x.head()

C:\Users\Public\Documents\ESTsoft\CreatorTemp/ipykernel_6796/3903930089.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_x['주상병알파벳'] = alnum


연령대코드  성별코드  주상병알파벳
0     12     2      13
1     12     2       5
2     12     2      14
3     12     2       5
4     12     2       8

In [11]:
# 나머지 숫자만 추출
num = []
for i in data['주상병코드']:
    num.append(i[1:])
num

['751',
 '1164',
 '308',
 '1164',
 '6531',
 '751',
 '751',
 '751',
 '751',
 '751',
 '751',
 '171',
 '751',
 '751',
 '751',
 '1164',
 '751',
 '751',
 '5422',
 '060',
 '751',
 '6500',
 '751',
 '1164',
 '751',
 '751',
 '1164',
 '751',
 '751',
 '1164',
 '751',
 '308',
 '751',
 '060',
 '751',
 '1164',
 '6500',
 '751',
 '751',
 '060',
 '751',
 '751',
 '751',
 '751',
 '751',
 '751',
 '_',
 '_',
 '_',
 '239',
 '_',
 '_',
 '_',
 '_',
 '_',
 '120',
 '120',
 '9348',
 '297',
 '308',
 '209',
 '219',
 '641',
 '641',
 '209',
 '_',
 '905',
 '_',
 '641',
 '641',
 '_',
 '209',
 '641',
 '40',
 '042',
 '0204',
 '40',
 '2531',
 '2531',
 '780',
 '2582',
 '1621',
 '40',
 '722',
 '722',
 '042',
 '8080',
 '108',
 '780',
 '40',
 '2531',
 '511',
 '042',
 '0390',
 '039',
 '039',
 '039',
 '039',
 '341',
 '303',
 '180',
 '36',
 '610',
 '610',
 '610',
 '509',
 '610',
 '36',
 '610',
 '180',
 '4796',
 '099',
 '0200',
 '060',
 '209',
 '610',
 '0109',
 '0290',
 '109',
 '610',
 '610',
 '610',
 '610',
 '610',
 '109',
 '02

In [12]:
# 컬럼추가
data_x['주상병숫자'] = num
data_x.head()

C:\Users\Public\Documents\ESTsoft\CreatorTemp/ipykernel_6796/1333388202.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_x['주상병숫자'] = num


연령대코드  성별코드  주상병알파벳 주상병숫자
0     12     2      13   751
1     12     2       5  1164
2     12     2      14   308
3     12     2       5  1164
4     12     2       8  6531

In [13]:
data_x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4624144 entries, 0 to 4624143
Data columns (total 4 columns):
 #   Column  Dtype 
---  ------  ----- 
 0   연령대코드   int64 
 1   성별코드    int64 
 2   주상병알파벳  int64 
 3   주상병숫자   object
dtypes: int64(3), object(1)
memory usage: 141.1+ MB


In [14]:
# 주상병숫자 타입변경
data_x['주상병숫자'] = data_x['주상병숫자'].str.replace('_','9999').astype(np.int64)
data_x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4624144 entries, 0 to 4624143
Data columns (total 4 columns):
 #   Column  Dtype
---  ------  -----
 0   연령대코드   int64
 1   성별코드    int64
 2   주상병알파벳  int64
 3   주상병숫자   int64
dtypes: int64(4)
memory usage: 141.1 MB


C:\Users\Public\Documents\ESTsoft\CreatorTemp/ipykernel_6796/4219141877.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_x['주상병숫자'] = data_x['주상병숫자'].str.replace('_','9999').astype(np.int64)


#### 부상병코드 만들기

In [15]:
# 가장 앞 알파벳만 따로 추출
alpha2 = []
for i in data['부상병코드']:
    alpha2.append(i[0])
alpha2

['M',
 'N',
 'E',
 'N',
 'J',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'S',
 'M',
 'M',
 'M',
 'N',
 'M',
 'M',
 'K',
 'J',
 'M',
 'J',
 'M',
 'E',
 'M',
 'M',
 'E',
 'M',
 'M',
 'E',
 'M',
 'E',
 'M',
 'J',
 'M',
 'E',
 'J',
 'M',
 'M',
 'J',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'F',
 'F',
 'H',
 'F',
 'F',
 'F',
 'F',
 'F',
 'L',
 'L',
 'K',
 'K',
 'H',
 'J',
 'K',
 'K',
 'K',
 'J',
 'B',
 'H',
 'B',
 'K',
 'K',
 'B',
 'J',
 'K',
 'J',
 'E',
 'H',
 'J',
 'B',
 'K',
 'J',
 'H',
 'H',
 'J',
 'I',
 'I',
 'E',
 'K',
 'H',
 'K',
 'M',
 'B',
 'K',
 'E',
 'K',
 'E',
 'E',
 'E',
 'E',
 'N',
 'J',
 'J',
 'K',
 'K',
 'K',
 'K',
 'K',
 'K',
 'K',
 'K',
 'J',
 'M',
 'R',
 'L',
 'J',
 'J',
 'R',
 'K',
 'M',
 'E',
 'R',
 'R',
 'R',
 'R',
 'R',
 'E',
 'M',
 'E',
 'M',
 'I',
 'J',
 'J',
 'S',
 'J',
 'J',
 'J',
 'J',
 'J',
 'L',
 'H',
 'L',
 'J',
 'J',
 'K',
 'K',
 'H',
 'K',
 'M',
 'R',
 'K',
 'K',
 'K',
 'R',
 'K',
 'K',
 'R',
 'T',
 'K',
 'M',
 'T',
 'R',
 'J',
 'M',
 'J',
 'M',
 'K',
 'M',
 'K'

In [16]:
# 숫자로 변환
alnum2 = []
for i in alpha2:
    alnum2.append(ord(i) - 64)
alnum2

[13,
 14,
 5,
 14,
 10,
 13,
 13,
 13,
 13,
 13,
 13,
 19,
 13,
 13,
 13,
 14,
 13,
 13,
 11,
 10,
 13,
 10,
 13,
 5,
 13,
 13,
 5,
 13,
 13,
 5,
 13,
 5,
 13,
 10,
 13,
 5,
 10,
 13,
 13,
 10,
 13,
 13,
 13,
 13,
 13,
 13,
 6,
 6,
 6,
 8,
 6,
 6,
 6,
 6,
 6,
 12,
 12,
 11,
 11,
 8,
 10,
 11,
 11,
 11,
 10,
 2,
 8,
 2,
 11,
 11,
 2,
 10,
 11,
 10,
 5,
 8,
 10,
 2,
 11,
 10,
 8,
 8,
 10,
 9,
 9,
 5,
 11,
 8,
 11,
 13,
 2,
 11,
 5,
 11,
 5,
 5,
 5,
 5,
 14,
 10,
 10,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 10,
 13,
 18,
 12,
 10,
 10,
 18,
 11,
 13,
 5,
 18,
 18,
 18,
 18,
 18,
 5,
 13,
 5,
 13,
 9,
 10,
 10,
 19,
 10,
 10,
 10,
 10,
 10,
 12,
 8,
 12,
 10,
 10,
 11,
 11,
 8,
 11,
 13,
 18,
 11,
 11,
 11,
 18,
 11,
 11,
 18,
 20,
 11,
 13,
 20,
 18,
 10,
 13,
 10,
 13,
 11,
 13,
 11,
 13,
 13,
 11,
 18,
 18,
 13,
 18,
 18,
 13,
 13,
 9,
 18,
 9,
 12,
 9,
 6,
 10,
 6,
 6,
 9,
 19,
 13,
 10,
 26,
 9,
 9,
 8,
 6,
 8,
 13,
 13,
 19,
 13,
 9,
 9,
 9,
 11,
 13,
 13,
 9,
 6,
 13,
 6,
 5,
 13,


In [17]:
# 컬럼 추가
data_x['부상병알파벳'] = alnum2
data_x.head()

연령대코드  성별코드  주상병알파벳  주상병숫자  부상병알파벳
0     12     2      13    751      13
1     12     2       5   1164      14
2     12     2      14    308       5
3     12     2       5   1164      14
4     12     2       8   6531      10

In [18]:
# 나머지 숫자만 추출
num2 = []
for i in data['부상병코드']:
    num2.append(i[1:])
num2

['750',
 '308',
 '1164',
 '308',
 '303',
 '750',
 '750',
 '750',
 '750',
 '750',
 '750',
 '134',
 '750',
 '750',
 '750',
 '308',
 '750',
 '750',
 '296',
 '068',
 '750',
 '209',
 '750',
 '785',
 '750',
 '750',
 '785',
 '750',
 '750',
 '785',
 '750',
 '785',
 '750',
 '068',
 '750',
 '785',
 '209',
 '750',
 '750',
 '068',
 '750',
 '750',
 '750',
 '750',
 '750',
 '750',
 '_',
 '_',
 '_',
 '109',
 '_',
 '_',
 '_',
 '_',
 '_',
 '500',
 '500',
 '297',
 '210',
 '1008',
 '029',
 '30',
 '599',
 '649',
 '0180',
 '_',
 '6500',
 '_',
 '649',
 '599',
 '_',
 '029',
 '649',
 '303',
 '069',
 '109',
 '303',
 '980',
 '760',
 '40',
 '108',
 '109',
 '029',
 '739',
 '7388',
 '069',
 '30',
 '109',
 '219',
 '2550',
 '980',
 '296',
 '069',
 '299',
 '785',
 '785',
 '785',
 '785',
 '411',
 '209',
 '209',
 '297',
 '297',
 '297',
 '297',
 '297',
 '297',
 '297',
 '297',
 '209',
 '766',
 '113',
 '238',
 '209',
 '343',
 '42',
 '296',
 '79108',
 '119',
 '42',
 '42',
 '42',
 '42',
 '42',
 '119',
 '79108',
 '119',
 '791

In [19]:
# 컬럼추가
data_x['부상병숫자'] = num2
data_x.head()

연령대코드  성별코드  주상병알파벳  주상병숫자  부상병알파벳 부상병숫자
0     12     2      13    751      13   750
1     12     2       5   1164      14   308
2     12     2      14    308       5  1164
3     12     2       5   1164      14   308
4     12     2       8   6531      10   303

In [20]:
data_x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4624144 entries, 0 to 4624143
Data columns (total 6 columns):
 #   Column  Dtype 
---  ------  ----- 
 0   연령대코드   int64 
 1   성별코드    int64 
 2   주상병알파벳  int64 
 3   주상병숫자   int64 
 4   부상병알파벳  int64 
 5   부상병숫자   object
dtypes: int64(5), object(1)
memory usage: 211.7+ MB


In [21]:
# 부상병숫자 타입변경
data_x['부상병숫자'] = data_x['부상병숫자'].str.replace('_','9999').astype(np.int64)
data_x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4624144 entries, 0 to 4624143
Data columns (total 6 columns):
 #   Column  Dtype
---  ------  -----
 0   연령대코드   int64
 1   성별코드    int64
 2   주상병알파벳  int64
 3   주상병숫자   int64
 4   부상병알파벳  int64
 5   부상병숫자   int64
dtypes: int64(6)
memory usage: 211.7 MB


In [22]:
data_x['입내원일수'] = data['입내원일수']
data_x.head()

연령대코드  성별코드  주상병알파벳  주상병숫자  부상병알파벳  부상병숫자  입내원일수
0     12     2      13    751      13    750      1
1     12     2       5   1164      14    308      1
2     12     2      14    308       5   1164      1
3     12     2       5   1164      14    308     21
4     12     2       8   6531      10    303      1

### feature 데이터 확인

In [23]:
data_x.head()

연령대코드  성별코드  주상병알파벳  주상병숫자  부상병알파벳  부상병숫자  입내원일수
0     12     2      13    751      13    750      1
1     12     2       5   1164      14    308      1
2     12     2      14    308       5   1164      1
3     12     2       5   1164      14    308     21
4     12     2       8   6531      10    303      1

### train test 구분하기

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(data_x.iloc[:,:6],
                                                    data_x.iloc[:,6:], test_size = 0.33)

In [26]:
from sklearn import tree
model = tree.DecisionTreeClassifier()
model

DecisionTreeClassifier()

In [27]:
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [29]:
from sklearn.metrics import classification_report, confusion_matrix

In [30]:
print(confusion_matrix(y_test, model.predict(X_test)))

[[    268    1641      14 ...       0       0       0]
 [   1038 1433173    1138 ...       0       0       0]
 [     31    3392     205 ...       0       0       0]
 ...
 [      0       1       0 ...       0       0       0]
 [      0       1       0 ...       0       0       0]
 [      0       5       0 ...       0       0       0]]


In [32]:
print(classification_report(y_test, model.predict(X_test)))

C:\Users\jhjh3\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\jhjh3\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\jhjh3\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\jhjh3\anaconda3\lib\site-packages\sklearn\metrics\_cla

              precision    recall  f1-score   support

           0       0.12      0.11      0.12      2402
           1       0.96      0.99      0.97   1447218
           2       0.12      0.05      0.07      3997
           3       0.18      0.09      0.12      6875
           4       0.16      0.07      0.09      2712
           5       0.10      0.04      0.06      2992
           6       0.19      0.09      0.12      1683
           7       0.26      0.07      0.11      7139
           8       0.07      0.02      0.04      1697
           9       0.05      0.02      0.03      1762
          10       0.12      0.04      0.06      2552
          11       0.03      0.01      0.02      1186
          12       0.08      0.03      0.05      1117
          13       0.03      0.01      0.01       804
          14       0.33      0.18      0.23      8911
          15       0.21      0.08      0.11      1979
          16       0.05      0.02      0.03       930
          17       0.02    

C:\Users\jhjh3\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\jhjh3\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [33]:
data_x['입내원일수'].unique()

array([  1,  21,  15,  14,   7,   3,   0,  17,   4,  19,   8,   2,  13,
         5,  11,  31,  20,  28,  18,  30,  26,  25,   9,   6,  22,  12,
        16,  34,  32,  90,  57,  10,  29,  37,  35,  38,  59,  56,  45,
        33,  46,  44,  70,  66, 108,  27,  23,  42,  62,  48,  84,  60,
        63,  41, 180,  58,  24,  39,  52,  49,  67,  40, 121, 120,  98,
       105,  65,  71,  43,  47, 112,  36,  64,  91, 101,  50,  95,  92,
       183,  54,  61,  99, 137, 100,  88,  78, 154,  93,  55,  76,  89,
       118, 126, 133,  77,  53,  80, 104,  85, 124,  51,  74, 182,  97,
       106,  69,  75,  68,  83,  86, 102,  81,  82, 150,  73, 103, 110,
       129, 136,  94,  72, 135, 210, 360,  79, 140, 200, 114, 181, 196,
       111, 117, 188, 170, 175, 147, 168, 122, 109, 116, 115, 198, 134,
        96, 151,  87, 193, 119, 153, 141, 107, 164, 123, 125, 127, 185,
       190, 113, 191, 217, 184, 189, 260, 130, 380, 224, 206, 187, 149,
       375, 225, 456, 194, 205, 201, 240, 690, 128, 300, 195, 33